### ISSUE TITLE
Allow folder structure for Webapps

### ISSUE THREAD

**Issue by tlunet** [Parallel-in-Time/time4apint#25]
Currently all webapps are stored in the same `web_apps` folder. As new apps are currently added, we need them to follow some repository structure in order to sort them (into categories, algorithms, etc ...).
It would be great that the `dynamic_site` code take into account such folder structure for the app :

```
- categ1 : folder for first category
    - index.md : small markdown page describing the categories and associated apps
    - app1.py : source code for app1
    - app1.md : extended documentation for app1
    - app2.py : source code for app2
    - app2.md : extended documentation for app2
- categ2 : folder for second category
    - ...
```

Then the API path should be like this :

```
baseURL : access to the main page, based on the README.md file from the git repo
baseURL/categ1 : access to the index page of categ1
baseURL/categ1/app1 : access to the webapp app1
...
```

In particular, this should be recursive and allow to define subcategories, with categories able to have simultaneously subcategories and webapps.

**Comment by MichelKrispin** [comment]
The folder structure should work now and it should (didn't test it yet) work recursively. The index files should be edited independently and as it seems the paths inside of it should be absolute. Relative paths might not work as intended because the routes `demo` and `demo/` both map to the demo index page but from there on relative paths differ.
